[
    {
        "adult": false,
        "backdrop_path": "/z6OkT7XjzSrgstiTlld0jUvME9y.jpg",
        "id": 726209,
        "title": "Leave the World Behind",
        "original_language": "en",
        "original_title": "Leave the World Behind",
        "overview": "A family's getaway to a luxurious rental home takes an ominous turn when a cyberattack knocks out their devices — and two strangers appear at their door.",
        "poster_path": "/l2bqoY9rgPAgugPkOTowIPIv61j.jpg",
        "media_type": "movie",
        "genre_ids": [
            9648,
            53,
            18
        ],
        "popularity": 190.385,
        "release_date": "2023-11-24",
        "video": false,
        "vote_average": 6.8,
        "vote_count": 95
    },
    {
        "adult": false,
        "backdrop_path": "/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
        "id": 466420,
        "title": "Killers of the Flower Moon",
        "original_language": "en",
        "original_title": "Killers of the Flower Moon",
        "overview": "When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.",
        "poster_path": "/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
        "media_type": "movie",
        "genre_ids": [
            80,
            18,
            36
        ],
        "popularity": 921.627,
        "release_date": "2023-10-18",
        "video": false,
        "vote_average": 7.7,
        "vote_count": 1186
    },
    {
        "adult": false,
        "backdrop_path": "/bFeooBowq3FfwLEaxRzcBKw5t7C.jpg",
        "id": 870358,
        "title": "Merry Little Batman",
        "original_language": "en",
        "original_title": "Merry Little Batman",
        "overview": "This Christmas, Damian Wayne wants to be a superhero like his dad – the one and only Batman. When Damian is left home alone while Batman takes on Gotham’s worst supervillains on Christmas Eve, he stumbles upon a villainous plot to steal Christmas and leaps at the chance to save the day.",
        "poster_path": "/2J70guF8wcErbYbRgZUBcvShgI1.jpg",
        "media_type": "movie",
        "genre_ids": [
            16,
            28,
            10751,
            35
        ],
        "popularity": 52.331,
        "release_date": "2023-12-08",
        "video": false,
        "vote_average": 7.7,
        "vote_count": 8
    },
    {
        "adult": false,
        "backdrop_path": "/aUfAbn4WXkioO5FPKAyxnVGaVqg.jpg",
        "id": 1023845,
        "title": "Silver and the Book of Dreams",
        "original_language": "de",
        "original_title": "Silber und das Buch der Träume",
        "overview": "When Liv moves to London, she meets the mysterious Henry and his group of friends, who pull her into the enthralling world of dream-travel. She and her newfound band of dream-wanderers conduct a ritual to make their biggest dream come true, but it demands the gravest sacrifice.",
        "poster_path": "/ycpxvpNyrkzsydwvLTUNixRWrdQ.jpg",
        "media_type": "movie",
        "genre_ids": [
            14,
            878,
            10749
        ],
        "popularity": 7.064,
        "release_date": "2023-11-06",
        "video": false,
        "vote_average": 5.846,
        "vote_count": 13
    },
    {
        "adult": false,
        "backdrop_path": "/dZiGxzXkYWZTaTjxmyT6rzV7ioF.jpg",
        "id": 1123093,
        "title": "Diary of a Wimpy Kid Christmas: Cabin Fever",
        "original_language": "en",
        "original_title": "Diary of a Wimpy Kid Christmas: Cabin Fever",
        "overview": "The winter holidays are turning out to be especially stressful for Greg Heffley this year. After accidentally damaging a snowplow while making a snowman with best friend Rowley Jefferson, Greg worries he won’t get the new video game console he so desperately wants for Christmas. To make matters worse, he gets snowed in with his family, including his grumpy older brother Rodrick and annoying younger brother Manny.",
        "poster_path": "/tV0996od52EJ6S8dLKvcVGsO7B.jpg",
        "media_type": "movie",
        "genre_ids": [
            16,
            35,
            10751
        ],
        "popularity": 58.422,
        "release_date": "2023-12-08",
        "video": false,
        "vote_average": 4.5,
        "vote_count": 3
    },
    {
        "adult": false,
        "backdrop_path": "/yOm993lsJyPmBodlYjgpPwBjXP9.jpg",
        "id": 787699,
        "title": "Wonka",
        "original_language": "en",
        "original_title": "Wonka",
        "overview": "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
        "poster_path": "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
        "media_type": "movie",
        "genre_ids": [
            35,
            10751,
            14
        ],
        "popularity": 1022.403,
        "release_date": "2023-12-06",
        "video": false,
        "vote_average": 6.808,
        "vote_count": 39
    },
    {
        "adult": false,
        "backdrop_path": "/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg",
        "id": 609681,
        "title": "The Marvels",
        "original_language": "en",
        "original_title": "The Marvels",
        "overview": "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
        "poster_path": "/3sXv15ymVkaV7E18m4TlTgwNkAN.jpg",
        "media_type": "movie",
        "genre_ids": [
            878,
            12,
            28
        ],
        "popularity": 499.826,
        "release_date": "2023-11-08",
        "video": false,
        "vote_average": 6.55,
        "vote_count": 616
    },
    {
        "adult": false,
        "backdrop_path": "/1b2qmBIO91k7STcZP6Dx0Q5snU5.jpg",
        "id": 1176139,
        "title": "Your Christmas or Mine 2",
        "original_language": "en",
        "original_title": "Your Christmas or Mine 2",
        "overview": "They've swapped Christmas – again. Can Hayley and James' relationship survive another turbulent family Christmas or has their future together gone off-piste?!",
        "poster_path": "/zswSOwzHmP90XXsbdcAIKhchOKL.jpg",
        "media_type": "movie",
        "genre_ids": [
            10749,
            35
        ],
        "popularity": 48.931,
        "release_date": "2023-12-07",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
    },
    {
        "adult": false,
        "backdrop_path": "/kG8iWrKGNlrUM7LfT6zJEOXglZd.jpg",
        "id": 945937,
        "title": "Fast Charlie",
        "original_language": "en",
        "original_title": "Fast Charlie",
        "overview": "When his aging mob boss is whacked, Charlie Swift, a loyal friend and hired gun, will stop at nothing to bring down the new crew coming up that took him out.",
        "poster_path": "/3y72ffwYRUPOj4yOQbiTaN897Tm.jpg",
        "media_type": "movie",
        "genre_ids": [
            28,
            53,
            80
        ],
        "popularity": 61.775,
        "release_date": "2023-12-08",
        "video": false,
        "vote_average": 7,
        "vote_count": 3
    },
    {
        "adult": false,
        "backdrop_path": "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
        "id": 872585,
        "title": "Oppenheimer",
        "original_language": "en",
        "original_title": "Oppenheimer",
        "overview": "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
        "poster_path": "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
        "media_type": "movie",
        "genre_ids": [
            18,
            36
        ],
        "popularity": 942.352,
        "release_date": "2023-07-19",
        "video": false,
        "vote_average": 8.14,
        "vote_count": 5261
    },
    {
        "adult": false,
        "backdrop_path": "/jBOyi3ibJbVa1imTCcddPUxTVAV.jpg",
        "id": 956920,
        "title": "There's Something in the Barn",
        "original_language": "no",
        "original_title": "There's Something in the Barn",
        "overview": "An American family fulfills their dream of moving back to their roots after inheriting a remote cabin in the mountains of Norway. But there's a surprise waiting for them.",
        "poster_path": "/axrzMJR5VPWYNiW9ArENiMEPTjr.jpg",
        "media_type": "movie",
        "genre_ids": [
            35,
            27,
            14
        ],
        "popularity": 78.876,
        "release_date": "2023-11-02",
        "video": false,
        "vote_average": 7.4,
        "vote_count": 35
    },
    {
        "adult": false,
        "backdrop_path": "/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg",
        "id": 670292,
        "title": "The Creator",
        "original_language": "en",
        "original_title": "The Creator",
        "overview": "Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.",
        "poster_path": "/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg",
        "media_type": "movie",
        "genre_ids": [
            28,
            12,
            18
        ],
        "popularity": 674.55,
        "release_date": "2023-09-27",
        "video": false,
        "vote_average": 7.1,
        "vote_count": 1346
    },
    {
        "adult": false,
        "backdrop_path": "/8GnWDLn2AhnmkQ7hlQ9NJUYobSS.jpg",
        "id": 695721,
        "title": "The Hunger Games: The Ballad of Songbirds & Snakes",
        "original_language": "en",
        "original_title": "The Hunger Games: The Ballad of Songbirds & Snakes",
        "overview": "64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.",
        "poster_path": "/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg",
        "media_type": "movie",
        "genre_ids": [
            28,
            10749,
            18
        ],
        "popularity": 432.827,
        "release_date": "2023-11-15",
        "video": false,
        "vote_average": 7.307,
        "vote_count": 605
    },
    {
        "adult": false,
        "backdrop_path": "/35z8hWuzfFUZQaYog8E9LsXW3iI.jpg",
        "id": 335977,
        "title": "Indiana Jones and the Dial of Destiny",
        "original_language": "en",
        "original_title": "Indiana Jones and the Dial of Destiny",
        "overview": "Finding himself in a new era, and approaching retirement, Indy wrestles with fitting into a world that seems to have outgrown him. But as the tentacles of an all-too-familiar evil return in the form of an old rival, Indy must don his hat and pick up his whip once more to make sure an ancient and powerful artifact doesn't fall into the wrong hands.",
        "poster_path": "/Af4bXE63pVsb2FtbW8uYIyPBadD.jpg",
        "media_type": "movie",
        "genre_ids": [
            12,
            28
        ],
        "popularity": 320.454,
        "release_date": "2023-06-28",
        "video": false,
        "vote_average": 6.677,
        "vote_count": 2183
    },
    {
        "adult": false,
        "backdrop_path": "/45zVtZx6Tzx3RKeDziK25K9geFf.jpg",
        "id": 901362,
        "title": "Trolls Band Together",
        "original_language": "en",
        "original_title": "Trolls Band Together",
        "overview": "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
        "poster_path": "/sEaLO9s7CIN3fjz8R3Qksum44en.jpg",
        "media_type": "movie",
        "genre_ids": [
            16,
            10751,
            10402,
            14,
            35
        ],
        "popularity": 1504.831,
        "release_date": "2023-10-12",
        "video": false,
        "vote_average": 7.2,
        "vote_count": 313
    },
    {
        "adult": false,
        "backdrop_path": "/bWIIWhnaoWx3FTVXv6GkYDv3djL.jpg",
        "id": 940721,
        "title": "Godzilla Minus One",
        "original_language": "ja",
        "original_title": "ゴジラ-1.0",
        "overview": "In postwar Japan, a new terror rises. Will the devastated people be able to survive... let alone fight back?",
        "poster_path": "/hkxxMIGaiCTmrEArK7J56JTKUlB.jpg",
        "media_type": "movie",
        "genre_ids": [
            18,
            878,
            28
        ],
        "popularity": 538.934,
        "release_date": "2023-11-03",
        "video": false,
        "vote_average": 8.475,
        "vote_count": 80
    },
    {
        "adult": false,
        "backdrop_path": "/iWOELznrV438fmyJ02GG31dULRM.jpg",
        "id": 1214891,
        "title": "Blood Vessel",
        "original_language": "ig",
        "original_title": "Blood Vessel",
        "overview": "Brought together by chance, six people fleeing a town devastated by oil pollution stow away on a mysterious ship — not realizing the dangers that await.",
        "poster_path": "/8tRTHHmg3O6BfUyCoHarRg7LTwA.jpg",
        "media_type": "movie",
        "genre_ids": [
            53,
            18
        ],
        "popularity": 1.96,
        "release_date": "2023-12-08",
        "video": false,
        "vote_average": 7,
        "vote_count": 2
    },
    {
        "adult": false,
        "backdrop_path": "/AhmzDeQR3VF0Xp2dMVFPIOxNyFg.jpg",
        "id": 1100795,
        "title": "Mr. Monk's Last Case: A Monk Movie",
        "original_language": "en",
        "original_title": "Mr. Monk's Last Case: A Monk Movie",
        "overview": "Monk steps out of retirement as his stepdaughter's wedding turns tragic when her fiancé dies in a bungee jumping accident.",
        "poster_path": "/gj74sUGsPMg5qDQooh8GTs4MvbP.jpg",
        "media_type": "movie",
        "genre_ids": [
            9648,
            35,
            80
        ],
        "popularity": 49.225,
        "release_date": "2023-12-08",
        "video": false,
        "vote_average": 7.5,
        "vote_count": 4
    },
    {
        "adult": false,
        "backdrop_path": "/j63Clh2P6PKQQNDSruu3z7NPeNu.jpg",
        "id": 1202584,
        "title": "Christmas As Usual",
        "original_language": "no",
        "original_title": "Så var det jul igjen",
        "overview": "To celebrate their engagement, Thea takes Jashan home — but his Indian roots and her family's Norwegian traditions clash in a chaotic Christmas.",
        "poster_path": "/suDjK0qIsPoBNrAhWUtIjkIWx1G.jpg",
        "media_type": "movie",
        "genre_ids": [
            10749,
            35,
            18
        ],
        "popularity": 80.522,
        "release_date": "2023-12-06",
        "video": false,
        "vote_average": 5.735,
        "vote_count": 17
    },
    {
        "adult": false,
        "backdrop_path": "/sp6egj5NHHRGmCMdIoTNdbLwACR.jpg",
        "id": 1022964,
        "title": "Candy Cane Lane",
        "original_language": "en",
        "original_title": "Candy Cane Lane",
        "overview": "A man, determined to win the neighborhood's annual Christmas decorating contest, makes a pact with an elf to help him win. However, the elf casts a spell bringing the twelve days of Christmas to life, bringing chaos to the small, unsuspecting town.",
        "poster_path": "/2pYgOBtBaFxAELQGj6p86vuIhhG.jpg",
        "media_type": "movie",
        "genre_ids": [
            35,
            14,
            10751
        ],
        "popularity": 463.95,
        "release_date": "2023-11-29",
        "video": false,
        "vote_average": 6.335,
        "vote_count": 115
    }
]